include:
  - board: nice_nano
    shield: DecaDeca_L
  - board: nice_nano
    shield: DecaDeca_R
  - board: nice_nano
    shield: DecaDeca_Split_left
  - board: nice_nano
    shield: DecaDeca_Split_right
  - board: nice_nano

    shield: settings_reset
